### PR TITLE
remove deprecated strings for form types

### LINKED ISSUE #94: Filter render settings are deprecated!
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle                  3.23.0 3.23.0 The missing Symfony Admin Generator
sonata-project/admin-search-bundle           v1.0.0 v1.0.0 Implement Search Engine (ElasticSearch) inside Sonata Admin
sonata-project/block-bundle                  3.4.0  3.4.0  Symfony SonataBlockBundle
sonata-project/cache                         1.0.7  1.0.7  Cache library
sonata-project/cache-bundle                  2.3.1  2.3.1  This bundle provides caching services
sonata-project/classification-bundle         3.3.2  3.3.2  Symfony SonataClassificationBundle
sonata-project/core-bundle                   3.5.1  3.6.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle               2.2.1  2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions           1.0.2  1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-mongodb-admin-bundle 3.0.0  3.0.0  Symfony Sonata / Integrate Doctrine MongoDB ODM into the SonataAdminBundle
sonata-project/doctrine-orm-admin-bundle     3.1.4  3.1.7  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle           2.2.0  2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                      1.7.1  1.7.1  Lightweight Exporter library
sonata-project/formatter-bundle              3.2.3  3.2.3  Symfony SonataFormatterBundle
sonata-project/google-authenticator          1.1.0  1.1.0  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle                   2.3.2  2.3.2  Symfony SonataIntlBundle
sonata-project/media-bundle                  3.7.0  3.7.0  Symfony SonataMediaBundle
sonata-project/news-bundle                   3.1.2  3.1.2  Symfony SonataNewsBundle
sonata-project/notification-bundle           3.2.0  3.2.0  Symfony SonataNotificationBundle
sonata-project/page-bundle                   3.5.2  3.5.2  This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                    2.2.1  2.2.1  Symfony SonataSeoBundle
sonata-project/user-bundle                   3.3.0  3.5.0  Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle     v2.8.2  v2.8.2  Integrates Assetic into Symfony2              
symfony/monolog-bundle     v3.1.1  v3.1.2  Symfony MonologBundle
symfony/polyfill-apcu      v1.6.0  v1.6.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.6.0  v1.6.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.6.0  v1.6.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.6.0  v1.6.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7  v3.0.3  Symfony SwiftmailerBundle
symfony/symfony            v2.8.28 v3.3.10 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 5.6.31
```
## Subject

Filters `getRenderSettings` methods return deprecated strings (E.g `sonata_type_filter_choice`) instead of FormType::class. I am having a problem with deprecated Symofny warning.

`Accessing type \"sonata_type_filter_choice\" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name \"Sonata\\AdminBundle\\Form\\Type\\Filter\\ChoiceType\" instead`

Not: But this only happens with StringFilter, and I don't know why :)

## Steps to reproduce
Use `sonata_search_elastica_string` like:
```php
$datagridMapper->add('foo', 'sonata_search_elastica_string')
```
Check your logs, if it is enabled for deprecations

Shouldn't we change these filter settings to full type class names?

https://github.com/sonata-project/SonataAdminSearchBundle/blob/1.x/Filter/StringFilter.php#L68

### PR DESCRIPTION
**Pull request by codebach**
I am targeting this branch, because of the Symfony form deprecations.

Closes #94

## Changelog

```markdown
### Deprecated
- Using `time` and `range` property in subclasses of `Sonata\AdminSearchBundle\Filter\AbstractDateFilter` is deprecated. Please implement `getFilterTypeClass` method which will be an abstract method.

### Fixed
- Deprecated strings type class names usage.

```

## To do

 - [x] Update the tests
 - [x] Add an upgrade note

### CODE REVIEW

**Review by soullivaneuh — DISMISSED** [review]
I updated your changelog (must be on fixed section).

**Comment by greg0ire** [comment]
Please associate your fundingcircle.com email address with your Github account, or change the email in your commits to an address already associated with it.

**Review by core23 — DISMISSED** [review]

File: Filter/AbstractDateFilter.php [hunk 1]
```diff
@@ -132,18 +134,25 @@ public function getDefaultOptions()
...
     {
-        $name = 'sonata_type_filter_date';
+        $types = [
+            'sonata_type_filter_date' => DateType::class,
+            'sonata_type_filter_datetime' => DateTimeType::class,
+            'sonata_type_filter_date_range' => DateRangeType::class,
+            'sonata_type_filter_datetime_range' => DateTimeRangeType::class,
+        ];
+
+        $type = 'sonata_type_filter_date';
```
Comment (greg0ire) [inline Filter/AbstractDateFilter.php]: 🤔 the `sonata_type_filter` is useless now, and a bit confusing

Comment (greg0ire) [reply Filter/AbstractDateFilter.php]:
```php
<?php
switch (true) {
    case $this->time && $this->range:
        $type = DateTimeRangeType::class;
        break;

    case $this->time && !$this->range:
        $type = DateTimeType::class;
        break;

    case !$this->time && $this->range:
        $type = DateRangeType::class;
        break;

    default:
        $type = DateType::class;
}
```

Please tell me sincerely what you think. I like that because you get rid of the
string array.

Comment (codebach) [reply Filter/AbstractDateFilter.php]: Your code looks cleaner, but still violating SOLID principles. I didn't want to touch the original code actually. If I am going to change this, I will make it SOLID then ;)

Comment (greg0ire) [reply Filter/AbstractDateFilter.php]: `switch` is a code smell for OCP violation, but only in the case when you cannot predict the size of the array. Here there are 2 options, which means 4 combinations. But maybe you were thinking about the case when people add more options?

**Comment by greg0ire** [comment]
```diff
- remove deprecated stings for form types
+ remove deprecated strings for form types
```

File: Filter/AbstractDateFilter.php (hunk 1 above)
Comment (codebach) [reply Filter/AbstractDateFilter.php]: Yes, they can either add more options or new types, since this is allowed. The other thing is not nice with current code is that the inheritance with properties. 

> `switch` is a code smell for OCP violation

Indeed :D

Comment (greg0ire) [reply Filter/AbstractDateFilter.php]: Oh ok then... curious to see the new solution :)

Comment (codebach) [reply Filter/AbstractDateFilter.php]: @greg0ire can you please check, does it look better?

File: Filter/DateRangeFilter.php [hunk 2]
```diff
@@ -11,19 +11,15 @@
...
+class DateRangeFilter extends AbstractDateFilter implements RangeFilterInterface
+{
     /**
-     * This filter has time.
-     *
-     * @var bool
+     * {@inheritdoc}
      */
-    protected $time = false;
+    protected function getFilterTypeClass()
```
Comment (greg0ire) [inline Filter/DateRangeFilter.php]: I think you could make it final

File: Filter/AbstractDateFilter.php [hunk 3]
```diff
@@ -18,18 +18,9 @@
...
-    protected $range = false;
-
-    /**
-     * Flag indicating that filter will filter by datetime instead by date.
-     *
-     * @var bool
+     * @return string
      */
-    protected $time = false;
+    abstract protected function getFilterTypeClass();
```
Comment (greg0ire) [inline Filter/AbstractDateFilter.php]: Adding an abstract protected method to a non-final class is a BC-break for extending classes.
Please add a default implementation that will trigger a deprecation the child class does not implement it, and a `NEXT_MAJOR` comment asking to make it `abstract`

**Review by greg0ire — COMMENTED** [review]
Nice solution, I'm jealous for not thinking of it, but for my defense, I didn't have all the code in mind!

File: Filter/DateFilter.php [hunk 4]
```diff
@@ -11,19 +11,15 @@
...
-     */
-    protected $range = false;
-
-    /**
-     * This filter does not allow filtering by time.
-     *
-     * @var bool
+     * {@inheritdoc}
      */
-    protected $time = false;
```
Comment (greg0ire) [inline Filter/DateFilter.php]: This is a BC-break, please restore the properties, and see if they are changed in the constructor, and throw if they are.

File: Filter/DateRangeFilter.php [hunk 5]
```diff
@@ -11,19 +11,15 @@
...
 
+class DateRangeFilter extends AbstractDateFilter implements RangeFilterInterface
+{
     /**
-     * This filter has time.
-     *
-     * @var bool
+     * {@inheritdoc}
      */
-    protected $time = false;
```
Comment (greg0ire) [inline Filter/DateRangeFilter.php]: This one is not a BC-break because of the parent

File: Filter/DateRangeFilter.php (hunk 2 above)
Comment (greg0ire) [reply Filter/DateRangeFilter.php]: I'm a bit unsure about it though.

File: Tests/Filter/DateFilterTest.php [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+
+class DateFilterTest extends TestCase
+{
+    public function testGetFilterTypeClass()
+    {
+        $filter = new DateFilter();
+
+        $renderSettings = $filter->getRenderSettings();
+
+        $this->assertSame('Sonata\AdminBundle\Form\Type\Filter\DateType', $renderSettings[0]);
```
Comment (greg0ire) [inline Tests/Filter/DateFilterTest.php]: Please use the `::class` notation as much as you can.

File: Tests/Filter/DateFilterTest.php [hunk 7]
```diff
@@ -0,0 +1,27 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Sonata\AdminSearchBundle\Tests\Filter;
+
+use PHPUnit\Framework\TestCase;
+use Sonata\AdminSearchBundle\Filter\DateFilter;
+
+class DateFilterTest extends TestCase
```
Comment (OskarStark) [inline Tests/Filter/DateFilterTest.php]: please add `@author` tags to new classes

File: Filter/AbstractDateFilter.php [hunk 8]
```diff
@@ -132,18 +123,8 @@ public function getDefaultOptions()
...
-        $name = 'sonata_type_filter_date';
-
-        if ($this->time) {
-            $name .= 'time';
-        }
-
-        if ($this->range) {
-            $name .= '_range';
-        }
-
```
Comment (greg0ire) [inline Filter/AbstractDateFilter.php]: You should use the `switch` I proposed and throw a deprecation here when appropriate, and still honor the old values.

**Comment by greg0ire** [comment]
@sonata-project/contributors I told @codebach that removing `time` and `range` and no longer honoring them is a BC-break. Do you agree or is it an acceptable BC-break?

**Comment by codebach** [comment]
> @sonata-project/contributors I told @codebach that removing time and range and no longer honoring them is a BC-break. Do you agree or is it an acceptable BC-break?

Lets see what they say, in case I will rearrange code and add deprecations.

> Nice solution, I'm jealous for not thinking of it, but for my defense, I didn't have all the code in mind!

Thanks and of course by just looking at code changes, you can easily miss :)

File: Filter/DateRangeFilter.php (hunk 2 above)
Comment (codebach) [reply Filter/DateRangeFilter.php]: If we are not going to allow them to override this, then we make the class final, correct?

Comment (greg0ire) [reply Filter/DateRangeFilter.php]: Yeah but making the class final is a BC-break, while making a new method final isn't

Comment (codebach) [reply Filter/DateRangeFilter.php]: True. But in case if these are acceptable BC then the class is final. (Still waiting for @sonata-project/contributors to say if it acceptable )

**Comment by OskarStark** [comment]
> Do you agree or is it an acceptable BC-break?

I do!

**Comment by codebach** [comment]
@greg0ire I added some deprecation warnings, but removed old logic from `getRenderSettings`. Because it doesn't make sense to keep old logic since we are adding this method to return type class name. If someone overrides the properties, should override the `getRenderSettings` method as well. Otherwise it does not make sense. It is still a BC break but adding everywhere this deprecations is just writing unnecessary code.

If you still think we should add the old logic then I will just add some comments to add the  `getRenderSettings` to subclasses but not the actual code. Something like this:
```php
/**
 * NEXT_MAJOR: Uncomment this method
 */
//protected function getRenderSettings()
//{
    // return type
//}
```

**Comment by greg0ire** [comment]
> Please associate your fundingcircle.com email address with your Github account, or change the email in your commits to an address already associated with it.

Can you please address this?

**Comment by greg0ire** [comment]
Apart from this, I think this is good to merge.

**Comment by codebach** [comment]
> Can you please address this?

Done. Actually it was changed in git config, but stayed in the commit because I was rebasing it :)

**Comment by greg0ire** [comment]
Still doesn't look good. Make sure to reset the author when amending.
still not good

**Comment by greg0ire** [comment]
Alternatively, link your other email address to your account, it's good to have several addresses.

**Comment by codebach** [comment]
There was a mistake to amend, now it is ok. I prefer to use only one.

**Review by greg0ire — DISMISSED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by codebach** [comment]
Any other thing to do here, can we merge this?

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Woops, yes, sorry!

**Comment by codebach** [comment]
Thanks @greg0ire 
We will also need a new release. If possible I would say please :)

**Comment by greg0ire** [comment]
I'm asking @Soullivaneuh
